### PR TITLE
Adding Sacramento city and populating people.py

### PR DESCRIPTION
**Pull request by feydan**
I'm building off of work from a previous member at Code4Sac. I want to get some data in for Sacramento so that we can power a local Councilmatic application.

Previously tried this PR on python-legistar-scraper.  @fgregg pointed me to this repo.  See the PR for more details: https://github.com/opencivicdata/python-legistar-scraper/pull/71.

### CODE REVIEW

**Comment by feydan** [comment]
Bumping this - can I get this reviewed and merged?  @fgregg ? Anyone else?

**Comment by feydan** [comment]
Bumping this again.  I'd love to get this merged.

**Comment by fgregg** [comment]
Looks great. Sorry for the delay

**Comment by feydan** [comment]
@fgregg how often do the scrapers run?  Can I expect to see Sacramento added here: https://ocd.datamade.us/jurisdictions/ ?

**Comment by feydan** [comment]
Fun!  Well I plan to continuing powering through and figure out how to host Councilmatic ourselves.  

I'm finding it a bit difficult to navigate the documentation and understand the architecture.  Here are some things I'm tracking currently -- maybe you can clarify and point me to additional documentation.

- https://github.com/opencivicdata/imago - Open civic data api that powers Councilmatic.  Is it possible to use the scrapers to push to your hosted version of this?  Or do we have to host our own version of the api to power Councilmatic?
- This current scrapers project - used for scraping the legistar site (in our case) and pushing to the OCD API.  Again, can we configure this to push to your API, or only our own, self-hosted one?
-  https://github.com/datamade/councilmatic-starter-template - This is the front-end for the Councilmatic that displays information by pulling from the OCD API.

**Comment by reginafcompton** [comment]
Hi @feydan! Glad to see you're powering through. I'll quickly answer your questions:

* you have to host an API with Sacramento data: [take a look at how DataMade hosts ocd.datamade.us.](https://github.com/datamade/api.opencivicdata.org)
* see above
* that's right! once you populate an API with Sacramento data, then you'll be able to import it to a Councilmatic instance using the [`import_data` management command](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py).

Hope that helps – and good luck.

**Pull request merged**
