### PR TITLE
NYC events

### PR DESCRIPTION
**Pull request by fgregg**
This adds events scraper for nyc. Depends upon merging and deploying https://github.com/opencivicdata/python-legistar-scraper/pull/12

### CODE REVIEW

**Comment by fgregg** [comment]
ping @rshorey

**Comment by rshorey** [comment]
OK. I don't think we're currently running NY on our server. Is the whole scraper running locally for you? If so, I'm happy to kick it locally.

Also, given some shifting responsibilities post-Paul, definitely a good idea to ping me when you send in PRs for things in my domain - I'll def see them faster that way!

**Comment by fgregg** [comment]
The whole scraper (at least what I've written so far is working). It looks
like the scraper has at least run once:
http://api.opencivicdata.org/ocd-organization/389257d3-aefe-42df-b3a2-a0d56d0ea731/

Please kick it off again.

**Comment by rshorey** [comment]
you're totally right, it's running. I can't keep my cities straight these days :)

**Pull request merged**
