### PR TITLE
ny was failing due to mismatch between BASE_URL and BASEURL

### PR DESCRIPTION
**Pull request by rshorey**

### CODE REVIEW

**Comment by rshorey** [comment]
@fgregg NYC is now working, data is here: http://api.opencivicdata.org/events/?jurisdiction_id=ocd-jurisdiction/country:us/state:ny/place:new_york/government

Given other Sunlight obligations right now, we can't commit time to debugging municipal-level scrapers going forward. I'm going to add you as the maintainer of the projects you've worked on so you get email when they fail and give you permission to merge PRs in the municipal repo.

We'll still of course be doing general OCD infrastructure work and continuing our state work here.

**Comment by fgregg** [comment]
Hi Rachel,

Am I on the e-mails that let me know if a municipal scraper failed?

**Comment by rshorey** [comment]
don't think so - what e-mail do you want me to use? (feel free to ping me at my sunlight email if you don't want that in public github records forever)

**Comment by rshorey** [comment]
in case it's useful, the other municipal scrapers we have running are Ferguson MO and Miami-Dade county so no one duplicates that work.

**Pull request merged**
