### PR TITLE
synching up with pupa 5.2

### PR DESCRIPTION
**Pull request by fgregg**
Making a few small changes to scrapers to synch up with 5.2.

@evz there's a pupa 5.2 migration we need to run on the server. When that is good to go, I'll merge.

### CODE REVIEW

**Comment by jamesturk** [comment]
Just a note: if you're going from 9.3 to 9.4 (pre-JSONB to JSONB) you can't
just use a migration, the DB has to be recreated.

**Comment by fgregg** [comment]
I think we are 9.4 on the server, but @evz will know.

**Comment by jamesturk** [comment]
Unfortunately it's the models themselves that are incompatible w/o a
migration path, the pre-JSONB version was using django libs that don't work
in Django 1.9 and b/c of the way Django migrations work it can't generate
migrations for them.  I could hand write some pure SQL migrations if you
decide not to go the way of dropping/recreating the DB, but I'd probably
need a copy of the pre-0.5 db and a bit of time to figure it out.

**Comment by fgregg** [comment]
Ok, thanks for that context.

On Sat, Nov 28, 2015 at 4:49 PM, James Turk <notifications@github.com>
wrote:

> Unfortunately it's the models themselves that are incompatible w/o a
> migration path, the pre-JSONB version was using django libs that don't work
> in Django 1.9 and b/c of the way Django migrations work it can't generate
> migrations for them. I could hand write some pure SQL migrations if you
> decide not to go the way of dropping/recreating the DB, but I'd probably
> need a copy of the pre-0.5 db and a bit of time to figure it out.
>
> On Sun, Nov 29, 2015 at 12:42 AM, Forest Gregg <notifications@github.com>
> wrote:
>
> > I think we are 9.4 on the server, but @evz <https://github.com/evz> will
> > know.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/opencivicdata/scrapers-us-municipal/pull/90#issuecomment-160343454
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/pull/90#issuecomment-160343701>
> .
>



-- 
773.888.2718

**Comment by evz** [comment]
Yeah, we're on 9.4 on the server. I'll run the migration.

**Pull request merged**
