### PR TITLE
Feature/stlouis scrapers

### PR DESCRIPTION
**Pull request by jesseilev**
Scrape some additional things:
* committee memberships of people
* committee sponsorships of bills

### CODE REVIEW

**Comment by fgregg** [comment]
Running this locally now.

First thing: I would prefer to not add new dependencies, particularly if they are only going to be used by one project. How hard would it be to avoid using `nameparser`

Second, there are people who are members of committees who are not being scraped by `scrape_people` For example, Joseph Vaccaro. 

This is not allowed, all memberhips must refer to a person already yielded by `scrape_people`

**Comment by jesseilev** [comment]
Gotcha. 

I will remove that dependency and implement my own `nameparser`

Re: Joseph Vaccaro -- that's very strange, when I run locally he does get scraped as a Person. Who are the other missing people? Are there a lot?

**Comment by fgregg** [comment]
I think the Joseph Vacarro thing was a bug on my side. let me dig into that.


On Thu, Nov 19, 2015 at 3:01 PM, Jesse Levine <notifications@github.com>
wrote:

> Gotcha.
>
> I will remove that dependency and implement my own nameparser
>
> Re: Joseph Vaccaro -- that's very strange, when I run locally he does get
> scraped as a Person. Who are the other missing people? Are there a lot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/pull/88#issuecomment-158196515>
> .
>



-- 
773.888.2718

**Comment by fgregg** [comment]
So the Joseph Vacarro thing was an error on my end, I believe. Here are the real problem people:

````
               ~{"name": "Joseph Vollmer            "}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Jennifer Florida "}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Jennifer Florida"}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Marlene E Davis            "}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Shane  Cohn "}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Larry Arnowitz            "}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Lewis E. Reed"}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Jeffrey L Boyd "}
03:30 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Joe  Vaccaro "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Joseph D Roddy            "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Megan E. Green            "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Kacie Starr Triplett "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Frank Williamson "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Gregory Carter "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Jeffrey L Boyd"}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Samuel L Moore"}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Alfred Wessels, Jr. "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Lyda Krewson "}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Lewis E Reed"}
03:31 < SLACK> [DataMade OCD Scrapers] cannot resolve pseudo id to Person: 
               ~{"name": "Dionne Flowers            "}
```

**Comment by jesseilev** [comment]
Hmm ok. 

I fixed a couple of problems, so it might be good now.

Is there a better way I should be doing this (creating committee memberships)? Seems like using people's names to reference Person objects is very fragile. For example, see the most recent commit where I added a ridiculous hack to handle one particular recurring typo coming from the website.

The [tutorial](http://docs.opencivicdata.org/en/latest/scrape/people.html) has a hard-coded example with "John" and the Transportation Committee, but this is not super helpful-- the relationship between people and Committees is many-to-many, so I can't simply instantiate both objects in the same scope like they do there. I need some way of referencing back to a previously-created object.

I also see that other cities, e.g. [cleveland](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/cleveland/people.py) use a method called Legislator.add_committee_membership(), which takes the name of the committee, which might be a little better since committee names are probably more consistent than people's names. But I don't know where that Legislator class comes from-- I am unable to import it.

**Comment by jesseilev** [comment]
@fgregg Also if there's a way I can validate the results locally, so I don't have to bug you each time :), let me know.

When I run it, pupa scrapes everything but then craps out when trying to connect to the server (which I think is TBE because posting the new data should only happen form your end). But anyway, my scraper never complains about memberships referencing non-existent people, and I'm guessing that's just because the validation doesn't occur till sometime after trying to connect.

**Comment by fgregg** [comment]
Yes, to validate

* set up postgis
* create a database name of your choosing
* export a connection string to your local environment  `export DATABASE_URL=postgis://username:password@db_server/your_database_name` (I use `export DATABASE_URL=postgis://localhost/opencivicdata`
* initialize the database `pupa dbinit`
* scrape and update your database `pupa update st_louis`

Also, if you send me your e-mail address, I'll invite you to a slack channel on opencivicdata. fgregg@datamade.us

**Pull request merged**
