### PR TITLE
chicago legislative sessions maybe fixed

### PR DESCRIPTION
**Pull request by rshorey**
I hope this will fix it, but this takes too long to run to check locally. @fgregg if this looks OK to you, we can pull it in and give it a try in production?

### CODE REVIEW

**Comment by fgregg** [comment]
Looks good to me.

**Comment by rshorey** [comment]
ok, here goes nothing :)

**Comment by rshorey** [comment]
I'll kick it as soon as the build is complete

**Comment by rshorey** [comment]
failed again, but with a new error. I won't get to this till Monday, but @fgregg if you want to take a look go ahead.
Traceback (most recent call last):
  File "/opt/sunlightfoundation.com/pupa/pupa/importers/base.py", line 153, in resolve_json_id
    return self.json_to_db_id[json_id]
KeyError: 'Chicago City Council'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pupa", line 9, in 
    load_entry_point('pupa==0.4.1', 'console_scripts', 'pupa')()
  File "/opt/sunlightfoundation.com/pupa/pupa/cli/__main__.py", line 71, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/sunlightfoundation.com/pupa/pupa/cli/commands/update.py", line 244, in handle
    report['import'] = self.do_import(juris, args)
  File "/opt/sunlightfoundation.com/pupa/pupa/cli/commands/update.py", line 177, in do_import
    report.update(bill_importer.import_directory(datadir))
  File "/opt/sunlightfoundation.com/pupa/pupa/importers/base.py", line 166, in import_directory
    return self.import_data(json_stream())
  File "/opt/sunlightfoundation.com/pupa/pupa/importers/base.py", line 203, in import_data
    obj_id, what = self.import_item(data)
  File "/opt/sunlightfoundation.com/pupa/pupa/importers/base.py", line 223, in import_item
    data = self.prepare_for_db(data)
  File "/opt/sunlightfoundation.com/pupa/pupa/importers/bills.py", line 56, in prepare_for_db
    data.pop('from_organization'))
  File "/opt/sunlightfoundation.com/pupa/pupa/importers/base.py", line 155, in resolve_json_id
    raise UnresolvedIdError('cannot resolve id: {}'.format(json_id))
pupa.exceptions.UnresolvedIdError: cannot resolve id: Chicago City Council

**Comment by fgregg** [comment]
No idea! Don't really know that much about the DB importers.

**Comment by rshorey** [comment]
yeah, I think I fixed something like this in another one not too long ago, shouldn't take too long once I get a moment.

**Pull request merged**
