### PR TITLE
NYC Scrapers

### PR DESCRIPTION
**Pull request by fgregg**
This is going to be a long running PR for the development of the New York City Scraper.

### CODE REVIEW

**Comment by fgregg** [comment]
@paultag @rshorey I want to abstract the legistar stuff into a separate repo. Are you amenable to adding this as dependency to `scrapers-us-municipal`?

**Comment by rshorey** [comment]
Any reason not to put it in a separate directory in this repo? I don't have much of an opinion either way, but I see some advantage of not needing to keep track of another repo if it's only going to be used by municipal scrapers. @paultag thoughts?

**Comment by fgregg** [comment]
@rshorey well everything else in this repo is a muncipality. I think I would like to write this so that's is not dependent on pupa, so it could be used in non OCD projects.

**Comment by paultag** [comment]
@fgregg @rshorey why don't we use https://github.com/opencivicdata/python-legistar-scraper ?

**Comment by paultag** [comment]
Also this PR doens't have a working scraper yet; did you open the PR on your right branch?

**Comment by fgregg** [comment]
`python-legistar-scraper` sounds good. 

Don't have a working scraper for NYC yet. Thought it would be convenient to have a long running PR here to discuss, but I can close and reeopen once I get a working scraper built.

**Comment by paultag** [comment]
Yeah, I use PRs as TODOs, so I'm going to close this, let's open it once it's working

**Pull request closed without merging**
