### PR TITLE
some agenda items don't have record numbers, scrape ALL the leg

### PR DESCRIPTION
**Pull request by fgregg**
Some agenda items have a blank record #.

### CODE REVIEW

**Comment by fgregg** [comment]
@rshorey @paultag I think this is ready to merge

**Comment by paultag** [comment]
@fgregg how long does this take to run?

**Comment by fgregg** [comment]
This will take about 24 hours? Too much?

**Comment by paultag** [comment]
Let's get other artifacts in before that - we might also reduce scrape
frequency if it takes that long - have you been able to run it all the way
through?

On Wed, May 20, 2015 at 5:49 PM, Forest Gregg <notifications@github.com>
wrote:

> This will take about 24 hours? Too much?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/pull/37#issuecomment-104049034>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
@paultag I haven't been able to set up everything yet to save locally. see https://github.com/opencivicdata/vagrant-opencivicdata.org/issues/8 and https://github.com/opencivicdata/opencivicdata/issues/11

**Comment by fgregg** [comment]
@paultag, with this latest commit, the scrape should take less than an hour. (for now).

**Comment by fgregg** [comment]
@paultag just ran this locally, and it takes just a little less than an hour.

**Comment by fgregg** [comment]
Thanks! How often does this scraper run?

**Comment by rshorey** [comment]
it's set to run every 24 hours. I'm going to kick it manually now. If the final scraper ends up taking a wicked long time, we will have to set it to run a bit less often.

**Pull request merged**
