### PR TITLE
NYC Person Scraper

### PR DESCRIPTION
**Pull request by fgregg**
This NYC Person Scraper is working locally 

It depends on https://github.com/opencivicdata/python-legistar-scraper/pull/11

### CODE REVIEW

**Comment by paultag** [comment]
Sweet! Let's get this running!

**Comment by fgregg** [comment]
woot!

**Comment by fgregg** [comment]
Nothing seems to be showing up at http://api.opencivicdata.org/organizations/?jurisdiction=ocd-jurisdiction/country:us/state:ny/place:new_york/government

Has the scraper run yet?

**Comment by paultag** [comment]
Yeah, it's run, but it's failing due to legistar import errors, I think.

I'll take a look into it

On Wed, Jun 17, 2015 at 2:47 PM, Forest Gregg <notifications@github.com>
wrote:

> Nothing seems to be showing up at
> http://api.opencivicdata.org/organizations/?jurisdiction=ocd-jurisdiction/country:us/state:ny/place:new_york/government
>
> Has the scraper run yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/pull/50#issuecomment-112911507>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
Thanks!

**Comment by paultag** [comment]
(BTW; you can reproduce this with `docker run`, since that's what we use -
if you want to check if something is failing, that's a good first-pass)

On Wed, Jun 17, 2015 at 3:16 PM, Forest Gregg <notifications@github.com>
wrote:

> Thanks!
>
> On Wed, Jun 17, 2015 at 2:07 PM <notifications@github.com> wrote:
>
> > Yeah, it's run, but it's failing due to legistar import errors, I think.
> >
> > I'll take a look into it
> >
> > On Wed, Jun 17, 2015 at 2:47 PM, Forest Gregg <notifications@github.com>
> > wrote:
> >
> > > Nothing seems to be showing up at
> > >
> >
> http://api.opencivicdata.org/organizations/?jurisdiction=ocd-jurisdiction/country:us/state:ny/place:new_york/government
> > >
> > > Has the scraper run yet?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/opencivicdata/scrapers-us-municipal/pull/50#issuecomment-112911507
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Paul Tagliamonte
> > Software Developer | Sunlight Foundation
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/opencivicdata/scrapers-us-municipal/pull/50#issuecomment-112916180
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/pull/50#issuecomment-112917801>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by paultag** [comment]
http://api.opencivicdata.org/organizations/?jurisdiction=ocd-jurisdiction/country:us/state:ny/place:new_york/government now showing sweet sweet data

**Comment by fgregg** [comment]
Nice!!!!

**Pull request merged**
